### ISSUE TITLE
Poppet on Windows?

### ISSUE THREAD

**Issue by LiamKenyon** [unifispot/poppet#6]
Hello,

First all great product.

I was wondering (as our current production setup in on Windows), can Poppet run on Windows?

If via a docker VM etc... but because its on the same PC as the controller will in work?

Liam

**Comment by unifispot** [comment]
Hey;

I am not sure if it can run fine on windows setup, but a VM would be fine. Same PC shouldn't an issue, just need to configure Controller IP correctly in Settings. Also you might want to think about forwarding port 80 to VM IP to get it working.

I didn't get time to test in Docker, its one of TODO items for future.
