### ISSUE TITLE
Does it work with an Amazon hosted system?

### ISSUE THREAD

**Issue by LiamKenyon** [unifispot/poppet#9]
OK, 

After implementing this solution for site that had there Unifi controller internally they then told another customer of it, but issue is they host there solution on Amazon S3/AWS.

Would this work?

As i've had a little play around but struggling to get the AP's to show up.

Also I've got another client that only has there own site on unifi controller so site ID is "default" this also seems to be causing issues.

**Comment by unifispot** [comment]
hey;

It works perfectly on AWS. I have tested on EC2 instance running Ubuntu. What kind of issue are you facing?

**Comment by LiamKenyon** [comment]
Ok i'll explain the environment:

Unifi Controller - Windows Amazon EC2.
Unifispot - Central Linux Server

Currently having issues connecting the two to talk to each other..

I may not entering the correct Host/IP but unsure.

As if i could get this working i'd be able to have it all centralised instead of segregating it out.

**Comment by unifispot** [comment]
It should work theoretically, just make sure you have added correct security policies for both machines to talk to each other.

However you won't be able to run unifispot in a windows server though. Best bet will be to run Controller and Unifispot on Ubuntu.

**Comment by LiamKenyon** [comment]
Yeah, i know in theory it should work but hitting a stubbling block somewhere.

Also yeah the unifispot is ran on a Linux Server we host while unifi is on a windows server (we could migrate but we have over 100+ clients on it).

Will keep trying to get it working and post my findings.

**Comment by LiamKenyon** [comment]
OK, still slightly struggling to get it working.

In the Host section do i put the URL of the AWS server?
And the IP enter the I given to the server?

As if so it's struggling to connect.

(bare in mind the Unifispot server is stored separate).

**Comment by unifispot** [comment]
Both Hostname and Ip address of the controller should be given.

FYI, some features (session monitoring, BW  limitation etc) won't work unless poppet is installed on the same server as controller.

**Comment by LiamKenyon** [comment]
Yeah thats fine, i'm trying to get the concept to work as we have a handle of customers who are on our hosted environment instead of there own server.
